apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-secrets-operator
      version: '0.9.x'
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault-secrets-operator-system
  values:
    defaultVaultConnection:
      enabled: true
      address: "http://vault.vault:8200"