apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foundry-vtt
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/apps/foundry-vtt/overlays/highmountain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: csi-driver-smb