---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1002
      - PGID=10000
      - TZ=EST/UTC
    volumes:
      - /opt/jelly-config:/config
      - /jelly-media/anime:/data/anime
      - /jelly-media/audiobooks:/data/audiobooks
      - /jelly-media/books:/data/books
      - /jelly-media/home-media:/data/home-media
      - /jelly-media/movies:/data/movies
      - /jelly-media/music:/data/music
      - /jelly-media/tv-shows:/data/tvshows
    ports:
      - 80:8096
      - 8920:8920
      - 7359:7359/udp
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: unless-stopped

