apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - vault.yaml
  - foundry-vaultsecret.yaml
  - smb-vaultsecret.yaml
  - storageclass.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml