apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt-data
  namespace: foundry-vtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb
  resources:
    requests:
      storage: 50Gi