apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.86.207/kubernetes"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "foundry-vtt"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "foundry-vtt"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=3.1.1
  - rw
  - nobrl
  - serverino
  - mfsymlinks
  - uid=421
  - gid=421
  - dir_mode=0775
  - file_mode=0775