apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infrastructure/csi-driver-smb/overlays/highmountain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
