apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-secrets-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infrastructure/vault-secrets-operator/overlays/highmountain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
